language: python
python:
  - "3.6"
  - "nightly"
virtualenv:
    system_site_package: true
install: 
  pip install -r requirements.txt
script:
  python ./TextFormatter/main.py --test
  coverage run ./TextFormatter/main.py --test
script:
  coverage html
