language: python
python:
  - "3.6"
  - "nightly"
virtualenv:
    system_site_package: true
install: 
  pip install -r requirements.txt
before_script:
  cd ./TextFormatter/
script:
  coverage run main.py --test
after_script:
  coverage report
